export { Admin } from './admin/Admin'
export { Cart } from './cart/Cart'
export { Contact } from './contact/Contact'
export { Home } from './home/Home'
export { OrderHistory } from './orderHistory/OrderHistory'
export { Login } from './auth/login/Login'
export { Registration } from './auth/registration/Registration'
export { ResetPassword } from './auth/resetPassword/ResetPassword'
